# random seed
seed: 0

# re, bananas, npenas, ls, rs
optimizer: re
batch_size: 1
search_space: darts
dataset: shd
# output results to this directory
out_dir: run
epochs: 1

# parameters for the optimizers
search:
  gpu: 1
  checkpoint_freq: 1000
  # for all optimizers
  epochs: 3
  train_portion: 0.7

#   # additional params
  learning_rate: 0.025
  # learning_rate: 0.05
  learning_rate_min: 0.001
  momentum: 0.9
  weight_decay: 0.0003
  warm_start_epochs: 0
  grad_clip: 5
  arch_learning_rate: 0.03
  arch_weight_decay: 0.001
#   output_weights: True
  

evaluation:
  checkpoint_freq: 5000
  batch_size: 96
  learning_rate: 0.025
  learning_rate_min: 0.00
  momentum: 0.9
  weight_decay: 0.0003
  epochs: 1
  warm_start_epochs: 0
  grad_clip: 5
  train_portion: 1.
  data_size: 50000

  cutout: True
  cutout_length: 16
  cutout_prob: 1.0
  drop_path_prob: 0.2
  auxiliary_weight: 0.4
